import Head from "next/head";
import Container from "react-bootstrap/Container";
import { useEffect, useState } from 'react';
import { BrowserRouter as Router, Route, Routes  } from 'react-router-dom'; // Import Router
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import TableComponents from "@/components/TableComponents";
import Beneficiary from "@/components/details/beneficiary";

export default function Home() {

  const [isBrowser, setIsBrowser] = useState(false);

  useEffect(() => {
    setIsBrowser(true); // Check if running in the browser
  }, []);

  if (!isBrowser) {
    return null; // Render nothing on the server side
  }

  return (
    <>
      <Head>
        <title>Grants</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" className="py-4 px-3 mx-auto">
        <Header />
        <Router>
        <TableComponents />

        <Routes> {/* Use Routes to define paths */}
      
              <Route path="/details/:id" element={<Beneficiary />} />
        
        </Routes>

        </Router>
        <Footer />
      </Container>
    </>
  );
}
